import React, { useEffect } from "react";

import Header from "../../components/organisms/header/header.component";
import Footer from "../../components/organisms/footer/footer.component";
import { useStore } from "../../store";
import { Helmet } from "react-helmet";

const PrivacyPolicy = () => {
  const websiteContent = useStore((state) => state.websiteContent);
  useEffect(() => {
    window.scrollTo(0, 0);
  }, []);
  return (
    <div>
      <Helmet>
        <meta charSet="utf-8" />
        <title>
          Easy Captcha Job | EarnEasy24 Money App | Earn With Captcha App
        </title>
        <meta
          name="description"
          content="Unlock effortless earnings with the Easy Captcha Job app! Start earning money effortlessly today. Join now and earn with Captcha."
        />
        <meta
          name="keywords"
          content="earn with captcha app, easy captcha job app, earn easy money app"
        />
      </Helmet>
      <Header headersData={[]} />

      <div className="pb-20 mt-36 lg:px-52 px-10">
        <div className="flex flex-col items-center py-4 text-deepBlue  ">
          <span className="text-40 lg:text-54 font-cunia">Privacy Policy</span>
        </div>
        <div className="text-17 py-8 ">
          <ol>
            <li>
              <strong className="font-cunia text-deepBlue text-28">
                Introduction
              </strong>
            </li>
            <br />
          </ol>
          <p>
            Welcome to
            <span className="text-lightPink"> Earneasy24</span>
          </p>
          <br />
          <p>
            Earneasy24 (“us”, “we”, or “our”) operates{" "}
            <a className="text-lightPink" href="https://www.earneasy24.com/">
              www.earneasy24.com
            </a>{" "}
            (hereinafter referred to as “Service”). Our Privacy Policy governs
            your visit to{" "}
            <a className="text-lightPink" href="https://www.earneasy24.com/">
              www.earneasy24.com
            </a>{" "}
            and explains how we collect, safeguard, and disclose information
            that results from your use of our Service. We use your data to
            provide and improve Service. By using Service, you agree to the
            collection and use of information in accordance with this policy.
            Unless otherwise defined in this Privacy Policy, the terms used in
            this Privacy Policy have the same meanings as in our Terms and
            Conditions. Our Terms and Conditions (“Terms”) govern all use of our
            Service and together with the Privacy Policy constitutes your
            agreement with us (“Agreement”).
          </p>
          <br />
          <ol start="2">
            <li>
              <strong className="font-cunia text-deepBlue text-24">
                - Definitions
              </strong>
            </li>
            <br />
          </ol>
          <p>
            SERVICE means the
            <a className="text-lightPink" href="https://www.earneasy24.com/">
              {" "}
              www.earneasy24.com
            </a>{" "}
            website operated by Earneasy24 PERSONAL DATA means data about a
            living individual who can be identified from those data (or from
            those and other information either in our possession or likely to
            come into our possession). USAGE DATA is data collected
            automatically either generated by the use of Service or from the
            Service infrastructure itself (for example, the duration of a page
            visit). COOKIES are small files stored on your device (computer or
            mobile device). DATA CONTROLLER means a natural or legal person who
            (either alone or jointly or in common with other persons) determines
            the purposes for which and the manner in which any personal data
            are, or are to be, processed. For the purpose of this Privacy
            Policy, we are a Data Controller of your data.
          </p>
          <br />
          <p>
            DATA PROCESSORS (OR SERVICE PROVIDERS) means any natural or legal
            person who processes the data on behalf of the Data Controller. We
            may use the services of various Service Providers in order to
            process your data more effectively. DATA SUBJECT is any living
            individual who is the subject of Personal Data. THE USER is the
            individual using our Service. The User corresponds to the Data
            Subject, who is the subject of Personal Data.
          </p>
          <br />
          <ol start="3">
            <li>
              <strong className="font-cunia text-deepBlue text-24">
                - Information Collection and Use
              </strong>
            </li>
            <br />
          </ol>
          <p>
            We collect several different types of information for various
            purposes to provide and improve our Service to you.
          </p>
          <br />
          <p>
            <strong className="font-cunia text-deepBlue text-24">
              - Usage Data
            </strong>
          </p>
          <br />
          <p>
            We may also collect information that your browser sends whenever you
            visit our Service or when you access the Service by or through any
            device (“Usage Data”).
          </p>
          <br />
          <p>
            This Usage Data may include information such as your computer’s
            Internet Protocol address (e.g. IP address), browser type, browser
            version, the pages of our Service that you visit, the time and date
            of your visit, the time spent on those pages, unique device
            identifiers and other diagnostic data.
          </p>
          <br />
          <p>
            When you access Service with a device, this Usage Data may include
            information such as the type of device you use, your device unique
            ID, the IP address of your device, your device operating system, the
            type of Internet browser you use, unique device identifiers and
            other diagnostic data.
          </p>
          <br />
          <p>
            <strong className="font-cunia text-deepBlue text-24">
              - Tracking Cookies Data
            </strong>
          </p>
          <br />
          <p>
            We use cookies and similar tracking technologies to track the
            activity on our Service and we hold certain information.
          </p>
          <br />
          <p>
            Cookies are files with a small amount of data which may include an
            anonymous unique identifier. Cookies are sent to your browser from a
            website and stored on your device. Other tracking technologies are
            also used such as beacons, tags, and scripts to collect and track
            information and to improve and analyze our Service.
          </p>
          <br />
          <p>
            You can instruct your browser to refuse all cookies or to indicate
            when a cookie is being sent. However, if you do not accept cookies,
            you may not be able to use some portions of our Service.
          </p>
          <br />
          <p>
            <strong className="font-cunia text-deepBlue text-24">
              Examples of Cookies we use:
            </strong>
          </p>
          <br />
          <p>
            <span className="text-lightPink">0.1.</span> Session Cookies: We use
            Session Cookies to operate our Service.
          </p>
          <br />
          <p>
            <span className="text-lightPink">0.2.</span> Preference Cookies: We
            use Preference Cookies to remember your preferences and various
            settings.
          </p>
          <br />
          <p>
            <span className="text-lightPink">0.3.</span> Security Cookies: We
            use Security Cookies for security purposes.
          </p>
          <br />
          <p>
            <span className="text-lightPink">0.4.</span> Advertising Cookies:
            Advertising Cookies are used to serve you with advertisements that
            may be relevant to you and your interests.
          </p>
          <br />
          <p>
            <strong className="font-cunia text-deepBlue text-24">
              Other Data
            </strong>
          </p>
          <br />
          <p>
            While using our Service, we may also collect the following
            information: sex, age, date of birth, place of birth, passport
            details, citizenship, registration at the place of residence and
            actual address, telephone number (work, mobile), details of
            documents on education, qualification, professional training,
            employment agreements, NDA agreements, information on bonuses and
            compensation, information on marital status, family members, social
            security (or other taxpayer identification) number, office location,
            and other data.
          </p>
          <br />
          <ol start="5">
            <li>
              <strong className="font-cunia text-deepBlue text-24">
                Use of Data
              </strong>
            </li>
            <br />
          </ol>
          <p>Earneasy24 uses the collected data for various purposes:</p>
          <br />
          <p>
            <span className="text-lightPink">0.1.</span> to provide and maintain
            our Service;
          </p>
          <br />
          <p>
            <span className="text-lightPink">0.2.</span> to notify you about
            changes to our Service;
          </p>
          <br />
          <p>
            <span className="text-lightPink">0.3.</span> to allow you to
            participate in interactive features of our Service when you choose
            to do so;
          </p>
          <br />
          <p>
            <span className="text-lightPink">0.4.</span> to provide customer
            support;
          </p>
          <br />
          <p>
            <span className="text-lightPink">0.5.</span> to gather analysis or
            valuable information so that we can improve our Service;
          </p>
          <br />
          <p>
            <span className="text-lightPink">0.6.</span> to monitor the usage of
            our Service;
          </p>
          <br />
          <p>
            <span className="text-lightPink">0.7.</span> to detect, prevent and
            address technical issues;
          </p>
          <br />
          <p>
            <span className="text-lightPink">0.8.</span> to fulfill any other
            purpose for which you provide it;
          </p>
          <br />
          <p>
            <span className="text-lightPink">0.9.</span> to carry out our
            obligations and enforce our rights arising from any contracts
            entered into between you and us, including for billing and
            collection;
          </p>
          <br />
          <p>
            <span className="text-lightPink">0.10.</span> to provide you with
            notices about your account and/or subscription, including expiration
            and renewal notices, email-instructions, etc.;
          </p>
          <br />
          <p>
            <span className="text-lightPink">0.11.</span> to provide you with
            news, special offers, and general information about other goods,
            services, and events which we offer that are similar to those that
            you have already purchased or enquired about unless you have opted
            not to receive such information;
          </p>
          <br />
          <p>
            <span className="text-lightPink">0.12.</span> in any other way we
            may describe when you provide the information;
          </p>
          <br />
          <p>
            <span className="text-lightPink">0.13.</span> for any other purpose
            with your consent.
          </p>
          <br />
          <ol start="6">
            <li>
              <strong className="font-cunia text-deepBlue text-24">
                Retention of Data
              </strong>
            </li>
            <br />
          </ol>
          <p>
            We will retain your Personal Data only for as long as is necessary
            for the purposes set out in this Privacy Policy. We will retain and
            use your Personal Data to the extent necessary to comply with our
            legal obligations (for example, if we are required to retain your
            data to comply with applicable laws), resolve disputes, and enforce
            our legal agreements and policies.
          </p>
          <br />
          <p>
            We will also retain Usage Data for internal analysis purposes. Usage
            Data is generally retained for a shorter period, except when this
            data is used to strengthen the security or to improve the
            functionality of our Service, or we are legally obligated to retain
            this data for longer time periods.
          </p>
          <br />
          <ol start="7">
            <li>
              <strong className="font-cunia text-deepBlue text-24">
                Transfer of Data
              </strong>
            </li>
            <br />
          </ol>
          <p>
            Your information, including Personal Data, may be transferred to –
            and maintained on – computers located outside of your state,
            province, country or other governmental jurisdiction where the data
            protection laws may differ from those of your jurisdiction. If you
            are located outside India and choose to provide information to us,
            please note that we transfer the data, including Personal Data, to
            India and process it there. Your consent to this Privacy Policy
            followed by your submission of such information represents your
            agreement to that transfer.&nbsp;
          </p>
          <br />
          <p>
            Earneasy24 will take all the steps reasonably necessary to ensure
            that your data is treated securely and in accordance with this
            Privacy Policy and no transfer of your Personal Data will take place
            to an organization or a country unless there are adequate controls
            in place including the security of your data and other personal
            information.
          </p>
          <br />
          <ol start="8">
            <li>
              <strong className="font-cunia text-deepBlue text-24">
                Disclosure of Data{" "}
              </strong>
              <br />
              <br />
              <p>
                We may disclose personal information that we collect, or you
                provide:
              </p>
            </li>
            <br />
          </ol>
          <p>
            <span className="text-lightPink">0.1.</span> Disclosure for Law
            Enforcement.
          </p>
          <br />
          <p>
            Under certain circumstances, we may be required to disclose your
            Personal Data if required to do so by law or in response to valid
            requests by public authorities.
          </p>
          <br />
          <p>
            <span className="text-lightPink">0.2.</span> Business Transaction.
          </p>
          <br />
          <p>
            If we or our subsidiaries are involved in a merger, acquisition or
            asset sale, your Personal Data may be transferred.
          </p>
          <br />
          <p>
            <span className="text-lightPink">0.3.</span> Other cases. We may
            disclose your information also:
          </p>
          <br />
          <p>
            <span className="text-lightPink">0.3.1.</span> to our subsidiaries
            and affiliates;
          </p>
          <br />
          <p>
            <span className="text-lightPink">0.3.2.</span> to contractors,
            service providers, and other third parties we use to support our
            business;
          </p>
          <br />
          <p>
            <span className="text-lightPink">0.3.3.</span> to fulfill the
            purpose for which you provide it;
          </p>
          <br />
          <p>
            <span className="text-lightPink">0.3.4.</span> for the purpose of
            including your company’s logo on our website;
          </p>
          <br />
          <p>
            <span className="text-lightPink">0.3.5.</span> for any other purpose
            disclosed by us when you provide the information;
          </p>
          <br />
          <p>
            <span className="text-lightPink">0.3.6.</span> with your consent in
            any other cases;
          </p>
          <br />
          <p>
            <span className="text-lightPink">0.3.7.</span> if we believe
            disclosure is necessary or appropriate to protect the rights,
            property, or safety of the Company, our customers, or others.
          </p>
          <br />
          <ol start="9">
            <li>
              <strong className="font-cunia text-deepBlue text-24">
                Security of Data
              </strong>
            </li>
            <br />
          </ol>
          <p>
            The security of your data is important to us but remember that no
            method of transmission over the Internet or method of electronic
            storage is 100% secure. While we strive to use commercially
            acceptable means to protect your Personal Data, we cannot guarantee
            its absolute security.
          </p>
          <br />
          <ol start="10">
            <li>
              <strong className="font-cunia text-deepBlue text-24">
                Your Data Protection Rights
              </strong>
            </li>
            <br />
          </ol>
          <p>
            If you are a resident of India, you have certain data protection
            rights, covered by the Indian IT Act. We aim to take reasonable
            steps to allow you to correct, amend, delete, or limit the use of
            your Personal Data. If you wish to be informed what Personal Data we
            hold about you and if you want it to be removed from our systems,
            please email us at {websiteContent?.email} In certain circumstances,
            you have the following data protection rights:
          </p>
          <br />
          <p>
            <span className="text-lightPink">0.1.</span> the right to access,
            update or to delete the information we have on you;
          </p>
          <br />
          <p>
            <span className="text-lightPink">0.2.</span> the right of
            rectification. You have the right to have your information rectified
            if that information is inaccurate or incomplete;
          </p>
          <br />
          <p>
            <span className="text-lightPink">0.3.</span> the right to object.
            You have the right to object to our processing of your Personal
            Data;
          </p>
          <br />
          <p>
            <span className="text-lightPink">0.4.</span> the right of
            restriction. You have the right to request that we restrict the
            processing of your personal information;
          </p>
          <br />
          <p>
            <span className="text-lightPink">0.5.</span> the right to data
            portability. You have the right to be provided with a copy of your
            Personal Data in a structured, machine-readable and commonly used
            format;
          </p>
          <br />
          <p>
            <span className="text-lightPink">0.6.</span> the right to withdraw
            consent. You also have the right to withdraw your consent at any
            time where we rely on your consent to process your personal
            information;
          </p>
          <br />
          <p>
            Please note that we may ask you to verify your identity before
            responding to such requests. Please note, we may not able to provide
            Service without some necessary data.
          </p>
          <br />
          <p>
            You have the right to complain to a Data Protection Authority about
            our collection and use of your Personal Data.
          </p>
          <br />
          <ol start="11">
            <li>
              <strong className="font-cunia text-deepBlue text-24">
                Your Data Protection Rights
              </strong>
            </li>
            <br />
          </ol>
          <p>
            <span className="text-lightPink">0.1.</span> users can visit our
            site anonymously;
          </p>
          <br />
          <p>
            <span className="text-lightPink">0.2.</span> our Privacy Policy link
            includes the word “Privacy”, and can easily be found on the home
            page of our website;
          </p>
          <br />
          <p>
            <span className="text-lightPink">0.3.</span> users will be notified
            of any privacy policy changes on our Privacy Policy Page;
          </p>
          <br />
          <p>
            <span className="text-lightPink">0.4.</span> users are able to
            change their personal information by emailing us at
            {websiteContent?.email}
          </p>
          <br />
          <p>Our Policy on “Do Not Track” Signals:</p>
          <br />
          <p>
            We honor Do Not Track signals and do not track plant cookies, or use
            advertising when a Do Not Track browser mechanism is in place. Do
            Not Track is a preference you can set in your web browser to inform
            websites that you do not want to be tracked. You can enable or
            disable Do Not Track by visiting the Preferences or Settings page of
            your web browser.
          </p>
          <br />
          <ol start="12">
            <li>
              <strong className="font-cunia text-deepBlue text-20">
                Your Data Protection Rights under the Information Technology Act
                (2000) (“IT Act” India) to include Section 43A and Section 72A,
                which give a right to compensation for improper disclosure of
                personal information.
              </strong>
            </li>
            <br />
          </ol>
          <p>
            <span className="text-lightPink">0.1.</span> What personal
            information we have about you. If you make this request, we will
            return to you:
          </p>
          <br />
          <p>
            <span className="text-lightPink">0.0.1.</span> The categories of
            personal information we have collected about you.
          </p>
          <br />
          <p>
            <span className="text-lightPink">0.0.2.</span> The categories of
            sources from which we collect your personal information.
          </p>
          <br />
          <p>
            <span className="text-lightPink">0.0.3.</span> The business or
            commercial purpose for collecting or selling your personal
            information.
          </p>
          <br />
          <p>
            <span className="text-lightPink">0.0.4.</span> The categories of
            third parties with whom we share personal information.
          </p>
          <br />
          <p>
            <span className="text-lightPink">0.0.5.</span>The specific pieces of
            personal information we have collected about you.
          </p>
          <br />
          <p>
            <span className="text-lightPink">0.0.6.</span> A list of categories
            of personal information that we have sold, along with the category
            of any other company we sold it to. If we have not sold your
            personal information, we will inform you of that fact.&nbsp;
          </p>
          <br />
          <p>
            <span className="text-lightPink">0.0.7.</span> A list of categories
            of personal information that we have disclosed for a business
            purpose, along with the category of any other company we shared it
            with.
          </p>
          <br />
          <p>
            Please note, you are entitled to ask us to provide you with this
            information up to two times in a rolling twelve-month period. When
            you make this request, the information provided may be limited to
            the personal information we collected about you in the previous 12
            months.
          </p>
          <br />
          <p>
            <span className="text-lightPink">0.08.</span> To delete your
            personal information. If you make this request, we will delete the
            personal information we hold about you as of the date of your
            request from our records and direct any service providers to do the
            same. In some cases, the deletion may be accomplished through the
            de-identification of the information. If you choose to delete your
            personal information, you may not be able to use certain functions
            that require your personal information to operate.
          </p>
          <br />
          <p>
            <span className="text-lightPink">0.09.</span> To stop selling your
            personal information. We don’t sell or rent your personal
            information to any third party for any purpose. We do not sell your
            personal information for monetary consideration. However, under some
            circumstances, a transfer of personal information to a third party,
            or within our family of companies, without monetary consideration
            may be considered a “sale” under Indian law. You are the only owner
            of your Personal Data and can request disclosure or deletion at any
            time.
          </p>
          <br />
          <p>
            If you submit a request to stop selling your personal information,
            we will stop making such transfers. Please note, if you ask us to
            delete or stop selling your data, it may impact your experience with
            us, and you may not be able to participate in certain programs or
            membership services that require the usage of your personal
            information to function. But in no circumstances, we will
            discriminate against you for exercising your rights.&nbsp;
          </p>
          <br />
          <p>
            To exercise your Indian data protection rights described above,
            please send your request(s) by email: {websiteContent?.email} Your
            data protection rights, described above, are covered by the IT Act
            (India).
          </p>
          <br />
          <ol start="13">
            <li>
              <strong className="font-cunia text-deepBlue text-24">
                Service Providers
              </strong>
            </li>
            <br />
          </ol>
          <p>
            We may employ third party companies and individuals to facilitate
            our Service (“Service Providers”), provide Service on our behalf,
            perform Service-related services or assist us in analyzing how our
            Service is used.
          </p>
          <br />
          <p>
            These third parties have access to your Personal Data only to
            perform these tasks on our behalf and are obligated not to disclose
            or use it for any other purpose.
          </p>
          <br />
          <ol start="14">
            <li>
              <strong className="font-cunia text-deepBlue text-24">
                Analytics
              </strong>
            </li>
            <br />
          </ol>
          <p>
            We may use third-party Service Providers to monitor and analyze the
            use of our Service.
          </p>
          <br />
          <ol start="15">
            <li>
              <strong className="font-cunia text-deepBlue text-24">
                CI/CD tools
              </strong>
            </li>
            <br />
          </ol>
          <p>
            We may use third-party Service Providers to automate the development
            process of our Service.
          </p>
          <br />
          <ol start="16">
            <li>
              <strong className="font-cunia text-deepBlue text-24">
                Advertising
              </strong>
            </li>
            <br />
          </ol>
          <p>
            We may use third-party Service Providers to show advertisements to
            you to help support and maintain our Service.
          </p>
          <br />
          <ol start="17">
            <li>
              <strong className="font-cunia text-deepBlue text-24">
                Behavioral Re-marketing
              </strong>
            </li>
            <br />
          </ol>
          <p>
            We may use remarketing services to advertise on third party websites
            to you after you visited our Service. We and our third-party vendors
            use cookies to inform, optimize, and serve ads based on your past
            visits to our Service.
          </p>
          <br />
          <ol start="18">
            <li>
              <strong className="font-cunia text-deepBlue text-24">
                Payments
              </strong>
            </li>
            <br />
          </ol>
          <p>
            We may provide paid products and/or services within Service. In that
            case, we use third-party services for payment processing (e.g.
            payment processors). We will not store or collect your payment card
            details. That information is provided directly to our third-party
            payment processors whose use of your personal information is
            governed by their Privacy Policy. These payment processors adhere to
            the standards set by RBI.
          </p>
          <br />
          <ol start="19">
            <li>
              <strong className="font-cunia text-deepBlue text-24">
                Links to Other Sites
              </strong>
            </li>
            <br />
          </ol>
          <p>
            Our Service may contain links to other sites that are not operated
            by us. If you click a third party link, you will be directed to that
            third party’s site. We strongly advise you to review the Privacy
            Policy of every site you visit. We have no control over and assume
            no responsibility for the content, privacy policies, or practices of
            any third-party sites or services.&nbsp;
          </p>
          <br />
          <ol start="20">
            <li>
              <strong className="font-cunia text-deepBlue text-24">
                Children’s Privacy
              </strong>
            </li>
            <br />
          </ol>
          <p>
            Our Services are not intended for use by children under the age of
            18 (“Child” or “Children”). We do not knowingly collect personally
            identifiable information from children under 18. If you become aware
            that a child has provided us with Personal Data, please contact us.
            If we become aware that we have collected Personal Data from
            children without verification of parental consent, we take steps to
            remove that information from our servers.
          </p>

          <br />
          <ol start="20">
            <li>
              <strong className="font-cunia text-deepBlue text-24">Jobs</strong>
            </li>
            <br />
          </ol>
          <p>
            This Application and website contain only job and Government job
            information; we do not guarantee or provide any jobs.
          </p>
          <br />
          <ol start="21">
            <li>
              <strong className="font-cunia text-deepBlue text-24">
                Changes to This Privacy Policy
              </strong>
            </li>
            <br />
          </ol>
          <p>
            We may update our Privacy Policy from time to time. We will notify
            you of any changes by posting the new Privacy Policy on this page.
            We will let you know via email and/or a prominent notice on our
            Service, prior to the change becoming effective and update
            “effective date” at the top of this Privacy Policy. You are advised
            to review this Privacy Policy periodically for any changes. Changes
            to this Privacy Policy are effective when they are posted on this
            page.
          </p>
          <br />
          <ol start="22">
            <li>
              <strong className="font-cunia text-deepBlue text-24">
                Contact Us
              </strong>
            </li>
            <br />
          </ol>
          <p>
            If you have any questions about this Privacy Policy, please contact
            us by email:{" "}
            <span className="text-lightPink">{websiteContent?.email}</span>
          </p>
          <br />
        </div>
      </div>

      {/* Footer*/}
      <Footer />
    </div>
  );
};

export default PrivacyPolicy;
